FROM node:24-alpine

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

COPY . .
WORKDIR /app

COPY pnpm-lock.yaml package.json ./

RUN --mount=type=cache,target=/pnpm/store \
    pnpm fetch --frozen-lockfile

RUN --mount=type=cache,target=/pnpm/store \
    pnpm install --frozen-lockfile --offline

COPY . .

# Generate Prisma client
RUN pnpm db:generate

RUN pnpm prestart

# Ensure keys directory exists at runtime
RUN mkdir -p ./.keys

EXPOSE 3000

# Generate Prisma client, keys and start dev server with HMR
CMD [ "pnpm", "dev" ]
