paths:
  /api/auth/register:
    post:
      tags:
        - Auth
      summary: Register a new user
      description: Register a new user in the system
      operationId: registerUser
      requestBody:
        description: Register a new user
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterUserRequest'
        required: true
      responses:
        '201':
          description: Usuario registrado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterUserResponse'
        '400':
          description: Datos de entrada inválidos
        '422':
          description: Error de validación
        '500':
          description: Error interno del servidor
          
