export const ERROR_CODES = {
  DATA_VALIDATION: {
    MISSING_FIELDS: "DATA_VALIDATION.MISSING_FIELDS",
    INVALID_FIELDS: "DATA_VALIDATION.INVALID_FIELDS",
    UNKNOWN_VALIDATION_ERROR: "DATA_VALIDATION.UNKNOWN_VALIDATION_ERROR",
    INVALID_DATA: "DATA_VALIDATION.INVALID_DATA",
    EMAIL_NOT_VERIFIED: "DATA_VALIDATION.EMAIL_NOT_VERIFIED",
    AUTHORIZATION_HEADER_REQUIRED: "DATA_VALIDATION.AUTHORIZATION_HEADER_REQUIRED",
    INVALID_AUTHORIZATION_FORMAT: "DATA_VALIDATION.INVALID_AUTHORIZATION_FORMAT",
    TOKEN_EXPIRED: "DATA_VALIDATION.TOKEN_EXPIRED",
  },
  AUTH: {
    REFRESH_SESSION: {
      SESSION_NOT_FOUND: "AUTH.REFRESH_SESSION.SESSION_NOT_FOUND",
    },
    REGISTER: {
      USER_NO_CREATED: "AUTH.REGISTER.USER_NO_CREATED",
      VALIDATION: {
        NAME: {
          MIN_LENGTH: "AUTH.REGISTER.VALIDATION.NAME.MIN_LENGTH",
          MAX_LENGTH: "AUTH.REGISTER.VALIDATION.NAME.MAX_LENGTH",
          INVALID_FORMAT: "AUTH.REGISTER.VALIDATION.NAME.INVALID_FORMAT",
        },
        LASTNAME: {
          MIN_LENGTH: "AUTH.REGISTER.VALIDATION.LASTNAME.MIN_LENGTH",
          MAX_LENGTH: "AUTH.REGISTER.VALIDATION.LASTNAME.MAX_LENGTH",
          INVALID_FORMAT: "AUTH.REGISTER.VALIDATION.LASTNAME.INVALID_FORMAT",
        },
        EMAIL: {
          INVALID_FORMAT: "AUTH.REGISTER.VALIDATION.EMAIL.INVALID_FORMAT",
          MAX_LENGTH: "AUTH.REGISTER.VALIDATION.EMAIL.MAX_LENGTH",
        },
        PASSWORD: {
          MIN_LENGTH: "AUTH.REGISTER.VALIDATION.PASSWORD.MIN_LENGTH",
          MAX_LENGTH: "AUTH.REGISTER.VALIDATION.PASSWORD.MAX_LENGTH",
          INVALID_FORMAT: "AUTH.REGISTER.VALIDATION.PASSWORD.INVALID_FORMAT",
        },
      },
    },
    LOGIN: {
      INVALID_DATA_RECEIVED: "AUTH.LOGIN.INVALID_DATA_RECEIVED",
      USER_NOT_FOUND: "AUTH.LOGIN.USER_NOT_FOUND",
      INVALID_CREDENTIALS: "AUTH.LOGIN.INVALID_CREDENTIALS",
      VALIDATION: {
        EMAIL: {
          REQUIRED: "AUTH.LOGIN.VALIDATION.EMAIL.REQUIRED",
          INVALID_FORMAT: "AUTH.LOGIN.VALIDATION.EMAIL.INVALID_FORMAT",
          MAX_LENGTH: "AUTH.LOGIN.VALIDATION.EMAIL.MAX_LENGTH",
        },
        PASSWORD: {
          REQUIRED: "AUTH.LOGIN.VALIDATION.PASSWORD.REQUIRED",
          MIN_LENGTH: "AUTH.LOGIN.VALIDATION.PASSWORD.MIN_LENGTH",
        },
      },
    },
    LOGOUT: {
      USER_NOT_LOGGED_OUT: "AUTH.LOGOUT.USER_NOT_LOGGED_OUT",
      VALIDATION: {
        ACCESS_TOKEN: {
          REQUIRED: "AUTH.LOGOUT.VALIDATION.ACCESS_TOKEN.REQUIRED",
        },
        REFRESH_TOKEN: {
          REQUIRED: "AUTH.LOGOUT.VALIDATION.REFRESH_TOKEN.REQUIRED",
        },
      },
    },
    UPDATE_USER: {
      USER_NOT_UPDATED: "AUTH.UPDATE_USER.USER_NOT_UPDATED",
      VALIDATION: {
        SESSION_TOKEN: {
          REQUIRED: "AUTH.UPDATE_USER.VALIDATION.SESSION_TOKEN.REQUIRED",
          INVALID_FORMAT: "AUTH.UPDATE_USER.VALIDATION.SESSION_TOKEN.INVALID_FORMAT",
        },
        REFRESH_TOKEN: {
          REQUIRED: "AUTH.UPDATE_USER.VALIDATION.REFRESH_TOKEN.REQUIRED",
          INVALID_FORMAT: "AUTH.UPDATE_USER.VALIDATION.REFRESH_TOKEN.INVALID_FORMAT",
        },
        EMAIL: {
          INVALID_FORMAT: "AUTH.UPDATE_USER.VALIDATION.EMAIL.INVALID_FORMAT",
          MAX_LENGTH: "AUTH.UPDATE_USER.VALIDATION.EMAIL.MAX_LENGTH",
        },
        NEW_PASSWORD: {
          MIN_LENGTH: "AUTH.UPDATE_USER.VALIDATION.NEW_PASSWORD.MIN_LENGTH",
          MAX_LENGTH: "AUTH.UPDATE_USER.VALIDATION.NEW_PASSWORD.MAX_LENGTH",
          INVALID_FORMAT: "AUTH.UPDATE_USER.VALIDATION.NEW_PASSWORD.INVALID_FORMAT",
        },
        NEW_PASSWORD_CONFIRMATION: {
          REQUIRED_WITH_PASSWORD:
            "AUTH.UPDATE_USER.VALIDATION.NEW_PASSWORD_CONFIRMATION.REQUIRED_WITH_PASSWORD",
          MUST_MATCH:
            "AUTH.UPDATE_USER.VALIDATION.NEW_PASSWORD_CONFIRMATION.MUST_MATCH",
        },
        PHONE: {
          INVALID_FORMAT: "AUTH.UPDATE_USER.VALIDATION.PHONE.INVALID_FORMAT",
        },
        NAME_LASTNAME: {
          BOTH_REQUIRED: "AUTH.UPDATE_USER.VALIDATION.NAME_LASTNAME.BOTH_REQUIRED",
        },
      },
    },
    REQUEST_RESET_PASSWORD_EMAIL: {
      EMAIL_NOT_SENT: "AUTH.REQUEST_RESET_PASSWORD_EMAIL.EMAIL_NOT_SENT",
      VALIDATION: {
        EMAIL: {
          REQUIRED: "AUTH.REQUEST_RESET_PASSWORD_EMAIL.VALIDATION.EMAIL.REQUIRED",
          INVALID_FORMAT:
            "AUTH.REQUEST_RESET_PASSWORD_EMAIL.VALIDATION.EMAIL.INVALID_FORMAT",
          MAX_LENGTH:
            "AUTH.REQUEST_RESET_PASSWORD_EMAIL.VALIDATION.EMAIL.MAX_LENGTH",
        },
        REDIRECT_TO: {
          INVALID_FORMAT:
            "AUTH.REQUEST_RESET_PASSWORD_EMAIL.VALIDATION.REDIRECT_TO.INVALID_FORMAT",
          MAX_LENGTH:
            "AUTH.REQUEST_RESET_PASSWORD_EMAIL.VALIDATION.REDIRECT_TO.MAX_LENGTH",
        },
      },
    },
  },
} as const;

export type TErrorCodes = typeof ERROR_CODES;