components:
  schemas:
    RegisterUserResponse:
      type: object
      properties:
        user:
          type: object
          $ref: "#/components/schemas/UserResponse"

        accessToken:
          type: string
          description: Access token
          example: 123-abc-45678
          format: jwt

        refreshToken:
          type: string
          description: Refresh token
          example: 123-abc-45678
          format: jwt
